import type { Metadata } from "next";
import { Geist, Geist_Mono, Covered_By_Your_Grace, Montserrat, Lexend_Peta, Inter } from "next/font/google";
import { madeTommyOutline } from "@/assets/fonts";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexpeta = Lexend_Peta({
  variable: "--font-lexpeta",
  subsets: ["latin"]
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
});

const covGrace = Covered_By_Your_Grace({
  variable: "--font-covgrace",
  subsets: ["latin"],
  weight: "400"
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} 
                    ${geistMono.variable} 
                    ${covGrace.variable} 
                    ${montserrat.variable} 
                    ${lexpeta.variable} 
                    ${madeTommyOutline.variable} 
                    ${inter.variable} 
                    antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
